resolver: nightly-2018-06-29 #lts-9.0

packages:
  - location: .
  - location:
      git: git@github.com:idris-lang/Idris-dev
      commit: master
    extra-dep: true
flags:
  idris:
    FFI: true
    GMP: true

#extra-deps:
   #- binary-0.8.5.1
   #- cheapskate-0.1.1
  
#nix:
  #enable: false
  #shell-file: stack-shell.nix
